### ISSUE TITLE
Third party keyboards cover the last lines of a note

### ISSUE THREAD

**Issue by ghost** [standardnotes/iOS#24]
Clarification: On a note with at least 500 words or so, it is difficult to get the cursor to the end of the note.
The keyboard remains covering the last few lines. Or, even when positioning it at the end of a note, the keyboard remains covering any lines or words typed/added.

Reproduction: Have note with at least 500 words or so (you can use a Loren Ipsum generator if you don't) then attempt to verify with gboard or swiftkey. Both of which have this issue.

This issue is not present with the stock iOS keyboard. And I am not sure if it is an issue with the third party keyboards themselves, as I could not replicate this problem using the stock apple notes app.

**Comment by atmoio** [comment]
Can reproduce bug, thanks, will get this fixed.
