### ISSUE TITLE
Crash after logging in

### ISSUE THREAD

**Issue by threkk** [standardnotes/iOS#26]
**Model:** iPhone 7 128Gb
**Version:** 10.2.1
**Description:**
1. Download the app.
2. Open the app.
3. Login.
4. Crashes.
5. Try to open again, it displays the list view and then crashes again.

Content of the account:
![screen shot 2017-02-15 at 01 56 22](https://cloud.githubusercontent.com/assets/518481/22956404/26a1d366-f322-11e6-9844-053960931513.png)

**Comment by atmoio** [comment]
Hmm.. can't replicate. Do you by any chance have any extensions installed, either app extensions or backend extensions, like the Dropbox ext? Can you open your Standard File Dashboard from the Account menu and tell me how many data items you have?

**Comment by threkk** [comment]
I have Dropbox Sync and File attacher on the desktop version. In the iOS version, before deleting it the first time, I had enabled the touch id. 

In my standard file dashboard there are 5 items: 2 extensions, 2 notes (1 deleted) and 1 SF|Extension.

**Comment by atmoio** [comment]
Ah ok, ya that's the problem. I currently have a fix for this waiting for review from Apple. In the meantime, please manually delete the SF|Extension object (choose the without sync option), and then re-add it. Sorry for the inconvenience.

**Comment by threkk** [comment]
It works now :+1:

Which type of synchronisation did I delete?

**Comment by atmoio** [comment]
What do you mean? I think either would have done the trick actually.
