### ISSUE TITLE
Include extensions in iOS app

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/iOS#30]
Are there plans to add extension support to iOS and other mobile apps? The collaboration editor is brilliant, but cannot be used on mobile, so the use is limited.

**Comment by atmoio** [comment]
Jury's out. Two options are: keep mobile clients as light clients, allowing us to reasonably ensure quality and longevity, and keep costs down. Or, make mobile clients full-featured clients, increasing costs and complexity substantially, and decreasing longevity.

**Comment by jz709u** [comment]
Defining "light" is the real question.  we can keep the clients light meaning having basic features but what should the basic features include?  should extensions be part of the basic features?

**Comment by atmoio** [comment]
I'd say for now the decision is going to be no extensions. The main product of Standard Notes is the web/desktop app. The mobile clients are just convenience clients.
