### ISSUE TITLE
Improve tagging UI

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/iOS#31]
Using sliders to add and remove tags to a note on iOS is pretty unusual and not intuitive for iOS users. A more common way to manage tags on iOS would be checkmarks next to the tag to add and remove it from a note. To delete a tag from the list of tags, sliding to the left to reveal a "remove" option would be standard behavior.

**Comment by CR0CKER** [comment]
One more suggestion: The "Tags" button could be moved from the upper-left corner of the main screen to the main menu at the bottom of the screen, in between "Notes" and "Account", which don't need text labels btw.

**Comment by atmoio** [comment]
The reason for using sliders is that checkboxes are not a standard part of the iOS SDK, which means we would have had to build it from scratch, which means more complexity and more maintenance in the future. I'm an iOS user myself and I know this is unusual, but I think it's still understandable from a UX perspective. If Apple ever adds a checkbox item in their SDK, we'll definitely make the switch.
