### ISSUE TITLE
The first time the Return key is hit when opening a note, it jumps to the bottom.

### ISSUE THREAD

**Issue by rfrelow** [standardnotes/iOS#34]
The first time the Return key is hit when opening a note, it jumps to the bottom. Let me know if you need a video or anything like that.

**Comment by atmoio** [comment]
Hey, what do you mean by this? A video or step-by-step instructions would be helpful.

**Comment by rfrelow** [comment]
Sure!

1. Open Standard Notes on iOS
2. Create a new note
3. Add text that goes at least a few lines vertically on the page. For this example I simply typed "A" and hit Return, 5 times in a row. So it looked like this:

A
A
A
A
A

4. Exit the note by hitting the back button on the top left. We are now ready to test the bug.
5. Tap on the note to enter it
6. Try to add a new line (by hitting return) near the top of the note. For example:

A
A <----- Try to enter a new line here, by tapping and hitting "return"
A
A
A

7. Notice the bug. It will create a new line, but your cursor is now at the bottom of the page!

I hope this was clear enough. If not I'll see able making a video :)

**Comment by atmoio** [comment]
Wow, great instructions thank you. Can you check to see if version 1.1.3 (new update) fixes the issue? I am unable to reproduce it on this version, and that version contains a fix targeted at a very similar bug.

**Comment by rfrelow** [comment]
Fixed!

Thanks!! :D
