### ISSUE TITLE
"Leave a Review" button in menu, under "Feedback"

### ISSUE THREAD

**Issue by atmoio** [standardnotes/iOS#43]
Opens App Store, or uses the new review API

**Comment by flowinho** [comment]
Should definitely use the new functionality. It creates less friction. And why would you implement legacy functionality.

**Comment by atmoio** [comment]
Definitely. Haven't explored new API yet. Easy to work with?

**Comment by flowinho** [comment]
Absolutely. Its pretty much a single LOC

**Comment by atmoio** [comment]
93afb6cee53ccf8522334a6cd4182c4d0bf0e957

**Comment by flowinho** [comment]
@mobitar 
Looking good, however i suggest to inlcude a "Leave review" button inside the settings that takes the user directly to the AppStore.
