### ISSUE TITLE
Search bar in notes list

### ISSUE THREAD

**Issue by atmoio** [standardnotes/iOS#5]
Searches title/text

**Comment by beaugunderson** [comment]
This is a big one for me, too. Currently using nvNotes and I like the approach there (title bar press turns it into a text field for searching); it also has a small tag cloud at the top that's useful.

**Comment by jz709u** [comment]
anyone currently working on this?

**Comment by atmoio** [comment]
No I don't think so

**Comment by jz709u** [comment]
where exactly should this search be placed?
I was thinking of two ways.  One way is to place it in under the navigation bar sort of like the Apple stock mail app. and the notes filter when typing

**Comment by jz709u** [comment]
and the other is to have a button in the navigation bar which on press displays a separate search screen.

**Comment by atmoio** [comment]
I think inline would be cool, so that it filters as you type. Similar to stock Apple apps.
