### ISSUE TITLE
encrypted data export is plain text

### ISSUE THREAD

**Issue by jdorweiler** [standardnotes/iOS#7]
I tried exporting a note and noticed it's not encrypted.
- created a new note
- add some text to the body
- go to account, select export data, encrypted
- the `text` field in the email is plain text

**Comment by jz709u** [comment]
why should the text be encrypted?  how are you supposed to un encrypt the data after you receive the email?  isn't the data only encrypted on the device?

**Comment by user6529576559** [comment]
E-mail is not safe, it travels through providers. It doesn't make sense to store your notes encrypted then send it unencrypted through the world so everybody can snoop on it. Exporting your notes by sending it through e-mail could be done securely if the notes are first decrypted and then encrypted again with the user's public PGP key (doing these still on the client), and then send it out to the dragnet.

**Comment by atmoio** [comment]
Yup this is definitely a bug, notes should be encrypted (if you choose that option) on export. Will get fixed asap.

**Comment by jz709u** [comment]
Thanks!

**Comment by atmoio** [comment]
Just submitted update to App Store that should fix this issue.

**Comment by atmoio** [comment]
This update is now live in the App Store.
